### ISSUE TITLE
Election checklist: SC Dem primary (Feb. 3)

### ISSUE THREAD

**Issue by alykat** [nprapps/elections24-primaries#100]
Administrative
- [x] Find out when/if special coverage is scheduled
- [x] Staffing plan

Results
- [x] Make sure races are represented correctly in the site config
- [x] Account for any special conditions unique to this race (test AP testing advisories)
- [x] Test results on staging
- [ ] Coordinate state page intro text with Wash Desk
- [x] Comment out "live coverage" links from footer and nav

Station comms
- [x] Coordinate with Wash and Member Partnership on messaging
- [x] Pull relevant embed code(s) from customizer

Homepage and internal comms
- [ ] Update [homepage code snippets](https://github.com/nprapps/elections24-primaries/blob/main/etc/homepage.md) with relevant results embeds, liveblog links, etc.
- [ ] Update all relevant documentation (engagement doc, homepage tick-tock, liveblog strategy)

Seamus pages
- [x] Coordinate with Washington on redirect pages for the liveblog(s) and state results page(s)
- [x] If needed, create [state shape promo image](https://github.com/nprapps/elections24-primaries/issues/47). Add to [promo images folder](https://drive.google.com/drive/u/1/folders/1FCj47_lohCPI-kaU0R5NalQZLXKcAnml).
- [x] Results redirects: Add results embed and state promo image
- [x] Request redirects from onlinetech/sysadmins

Mobile apps
- [ ] Coordinate with mobile team that they have the correct embeds (Note: In our standard embed code, change it from a `p` tag to a `div`. Also, if they decide to use the liveblog headlines module, make sure to add the `pjax=false` param to the path.)
