### ISSUE TITLE
Election checklist: NV primaries/caucuses (Nov. 6 and 8)

### ISSUE THREAD

**Issue by alykat** [nprapps/elections24-primaries#113]
Administrative
- [x] Find out when/if special coverage is scheduled
- [x] Staffing plan

Results
- [x] Make sure races are represented correctly in the site config
- [x] Account for any special conditions unique to this race (test AP testing advisories)
- [x] Test results on staging
- [x] Coordinate state page intro text with Wash Desk

Station comms
- [x] Coordinate with Wash and Member Partnership on messaging
- [x] Pull relevant embed code(s) from customizer

~Homepage and internal comms~

~Liveblog~

Seamus pages
- [x] Coordinate with Washington on redirect pages for the liveblog(s) and state results page(s)
- [x] If needed, create [state shape promo image](https://github.com/nprapps/elections24-primaries/issues/47). Add to [promo images folder](https://drive.google.com/drive/u/1/folders/1FCj47_lohCPI-kaU0R5NalQZLXKcAnml).
- [x] Results redirects: Add results embed and state promo image
- [x] Request redirects from onlinetech/sysadmins

~Mobile apps~

~On election day~
