### ISSUE TITLE
Delegate tracker

### ISSUE THREAD

**Issue by alykat** [nprapps/elections24-primaries#12]
We had one for Dem candidates in 2020; would need to rework it to highlight GOP in 2024

**Comment by alykat** [comment]
Here's what we did in 2020:
https://www.npr.org/2020/02/10/799979293/how-many-delegates-do-the-2020-presidential-democratic-candidates-have

Data comes from AP's API, processed here:
https://github.com/search?q=repo%3Anprapps%2Felections24-primaries%20getDelegates&type=code

The 2020 delegate file was published here:
https://apps.npr.org/elections20-primaries/data/delegates.json

API documentation:
https://developer.ap.org/ap-elections-api/docs/#t=National_Presidential_Delegate_Reports.htm

Graphics were produced in the dgnext rig:
https://github.com/nprapps/graphics-archive/tree/master/2020/02/graphics-js/delegate-tracker-20200117

**Comment by hilaryfung** [comment]
Overall
- [ ] Enter all delegate events into [spreadsheet](https://docs.google.com/spreadsheets/d/1CijNuPQf_Uge2EjBaou-ds6Fqc5rgGRYiMjVhEStU-Q/edit#gid=275813995)
- [ ] Add chatter about number of delegates needed to clinch nomination

Line chart
- [ ] Use AP data from URL
- [ ] Make the start date Jan. 1, 2024 with only the candidates in the sheet
- [ ] Make today the end date

Table
- [ ] Add dates as sections
- [ ] For each state, add total number of delegates available
- [ ] Color in the winner in each row

Bar chart
- [ ] Use candidate colors
