### ISSUE TITLE
Election checklist: New Hampshire (Jan. 23)

### ISSUE THREAD

**Issue by alykat** [nprapps/elections24-primaries#83]
Administrative
- [x] Find out when/if special coverage is scheduled
- [x] Staffing plan

Results
- [x] Make sure races are represented correctly in the site config
- [x] Account for any special conditions unique to this race (check AP testing advisories)
- [x] Test results on staging
- [x] Coordinate state page intro text with Wash Desk

Station comms
- [x] Coordinate with Wash and Member Partnership on messaging
- [x] Pull relevant embed code(s) from customizer

Homepage and internal comms
- [x] Update [homepage code snippets](https://github.com/nprapps/elections24-primaries/blob/main/etc/homepage.md) with relevant results embeds, liveblog links, etc.
- [x] Update all relevant documentation (engagement doc, homepage tick-tock, liveblog strategy)

Liveblog
- [x] Coordinate with liveblog crew to make sure special branding makes it to the new blog(s)
- [x] Preload results embed(s) and any other relevant graphics into the liveblog tool. Preface each with `Election 2024:` in the asset name. Log in the [spreadsheet](https://docs.google.com/spreadsheets/d/1Elnl4JarzsK2JH5Jmr7vxSTDT9NobyVZTvMP3KNrDPs/edit#gid=869878592).
- [x] Add results embed to `Body` section of the liveblog

Seamus pages
- [x] Coordinate with Washington on redirect pages for the liveblog(s) and state results page(s)
- [x] If needed, create [state shape promo image](https://github.com/nprapps/elections24-primaries/issues/47). Add to [promo images folder](https://drive.google.com/drive/u/1/folders/1FCj47_lohCPI-kaU0R5NalQZLXKcAnml).
- [x] Liveblog redirects: Add liveblog headlines embed and "live updates" promo image
- [x] Results redirects: Add results embed and state promo image
- [x] Request redirects from onlinetech/sysadmins

Mobile apps
- [x] Coordinate with mobile team that they have the correct embeds (remember that the [liveblog headlines](https://github.com/nprapps/liveblog-headlines) module, when used in the app context, needs to use the `pjax=false` param)

On election day
- [x] Add liveblog link to results site topnav and footer
